repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Trims trailing white spaces
      - id: trailing-whitespace
      # Make line endings consistent
      - id: mixed-line-ending
      # Ensure that every file ends with a newline
      - id: end-of-file-fixer
      # Check for unresolved merge conflicts
      - id: check-merge-conflict
      # Detect file names that could cause conflicts on case-insensitive file
      # systems.
      - id: check-case-conflict
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff
        args: [--show-source]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff-format
        args: [--diff]
